version: '3.7'

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dump:/app/dump
    ports:
      - 3000:80
    depends_on:
      - api

  api:
    image: kennethreitz/httpbin
    ports:
      - 3001:80
